name: Update README with Dev.to Blog Posts

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install rss-parser

      - name: Fetch and update README
        run: |
          node -e "
          const fs = require('fs');
          const Parser = require('rss-parser');
          const parser = new Parser();
          
          (async () => {
            const feed = await parser.parseURL('https://dev.to/feed/arafatweb');
            let readmeContent = fs.readFileSync('README.md', 'utf8');
            let newBlogContent = '';
            feed.items.slice(0, 5).forEach(item => {
              newBlogContent += `## [${item.title}](${item.link})\\n`;
              newBlogContent += `![Image](${item.enclosure?.url || 'No image available'})\\n`;
              newBlogContent += `Description: ${item.contentSnippet}\\n\\n`;
            });
            
            const newReadme = readmeContent.replace(/<!-- BLOG-POST-LIST:START -->.*<!-- BLOG-POST-LIST:END -->/s, `<!-- BLOG-POST-LIST:START -->\\n${newBlogContent}<!-- BLOG-POST-LIST:END -->`);
            fs.writeFileSync('README.md', newReadme);
          })();"

